apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-lifebuild
spec:
  selector:
    matchLabels:
      app: server-lifebuild
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: server-lifebuild
        stage: production
        kuvel.azisaba.net/enable-server-discovery: "true"
        kuvel.azisaba.net/preferred-server-name: lifebuild
    spec:
      nodeName: saba12
      containers:
      - name: server-lifebuild
        # Dockerイメージの指定
        # java11の11の部分を8にしたり17にしたりなど、Minecraftバージョンによって適宜変えてください
        # Javaバージョン早見表
        # 1.14.4以下 ... 8
        # 1.15.x ... 8-11 (9-10はサポート終了)
        # 1.16.x ... 11-16 (12-16はサポート終了)
        # 1.17.x ... 16-17 (16はサポート終了)
        # 1.18.x～1.20.4 ... 17
        # 1.20.5以降 ... 21
        image: itzg/minecraft-server:java21
        workingDir: /data
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
        ports:
          - containerPort: 25565
        env:
          # タイムゾーン
          - name: TZ
            value: "Asia/Tokyo"
          # EULAに同意する
          - name: EULA
            value: "true"
          # サーバーの種類
          - name: TYPE
            value: PAPER
          # 最適化されたJVMフラグを使用する
          - name: USE_AIKAR_FLAGS
            value: "true"
          # スポーン保護
          - name: SPAWN_PROTECTION
            value: "0"
          # オンラインモード
          - name: ONLINE_MODE
            value: "false"
          # コマンドブロックを有効にする
          - name: ENABLE_COMMAND_BLOCK
            value: "true"
          # ネザーを有効にする
          - name: ALLOW_NETHER
            value: "false"
          # "Flying is not enabled on this server"を有効にする
          - name: ALLOW_FLIGHT
            value: "false"
          # 描画距離
          - name: VIEW_DISTANCE
            value: "10"
          # 統計情報をMojangに送信する
          - name: SNOOPER_ENABLED
            value: "false"
          # プレイヤーの実績・進捗解除を全体チャットに流す
          - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
            value: "false"
          # 最大人数
          - name: MAX_PLAYERS
            value: "1000"
          # UID (変更しないでください)
          - name: UID
            value: "0"
          # GID
          - name: GID
            value: "1015"
          # Minecraftバージョン
          - name: VERSION
            value: 1.15.2
          # 初期・最大メモリ
          - name: MAX_MEMORY
            value: 4G
          # ホワイトリスト
          - name: ENABLE_WHITELIST
            value: "false"
          # Add debugger
          - name: JVM_OPTS
            value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -DPaper.IgnoreJavaVersion=true"
          # yml内のCFG_なんとかを置き換えるためのもの
          - name: ENV_VARIABLE_PREFIX
            value: "CFG_"
          # メタデータ(サーバー内で環境変数で取得可能)
          - name: CFG_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CFG_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CFG_SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
        startupProbe:
          tcpSocket:
            port: 25565
          failureThreshold: 60 # 600秒
          periodSeconds: 10
        volumeMounts:
        - name: server-data
          mountPath: /data
          readOnly: false
        - name: tab-config
          mountPath: /plugins/TAB/config.yml
          subPath: config.yml
        - name: raid-storage
          mountPath: /mnt/raid/srv/lifebuild
      volumes:
      - name: server-data
        hostPath:
          path: /srv/lifebuild
          type: Directory
      - name: tab-config
        configMap:
          name: common-life-server-tab-config
      - name: raid-storage
        hostPath:
          path: /mnt/raid/srv/lifebuild
          type: Directory
      priorityClassName: minecraft-other-server
      terminationGracePeriodSeconds: 60 # 1分
---
apiVersion: v1
kind: Service
metadata:
  name: server-lifebuild-svc
spec:
  type: ClusterIP
  selector:
    app: server-lifebuild
    stage: production
  ports:
    - port: 25565
      targetPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: lifebuild-debugger-svc
spec:
  type: NodePort
  selector:
    app: server-lifebuild
    stage: production
  ports:
    - name: debugger-port
      port: 30598
      targetPort: 5005
      nodePort: 30598
