apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-lifetown
spec:
  selector:
    matchLabels:
      app: server-lifetown
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: server-lifetown
        stage: production
        kuvel.azisaba.net/enable-server-discovery: "true"
        kuvel.azisaba.net/preferred-server-name: lifetown
    spec:
      nodeName: saba9
      containers:
      - name: server-lifetown
        # Dockerイメージの指定
        # java11の11の部分を8にしたり17にしたりなど、Minecraftバージョンによって適宜変えてください
        # Javaバージョン早見表
        # 1.14.4以下 ... 8
        # 1.15.x ... 8-11 (9-10はサポート終了)
        # 1.16.x ... 11-16 (12-16はサポート終了)
        # 1.17.x ... 16-17 (16はサポート終了)
        # 1.18.x～1.20.4 ... 17 (一部は21まで可能)
        # 1.20.5以降 ... 21
        image: itzg/minecraft-server:java21
        workingDir: /data
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1000m"
            memory: "6Gi"
          limits:
            cpu: "10000m"
            memory: "16Gi" # (MAX_)MEMORY + 4Gぐらいにするのがいいらしい
        ports:
          - containerPort: 25565
          - containerPort: 8100
        env:
          # タイムゾーン
          - name: TZ
            value: "Asia/Tokyo"
          # EULAに同意する
          - name: EULA
            value: "true"
          # サーバーの種類
          - name: TYPE
            value: PAPER
          # 最適化されたJVMフラグを使用する
          - name: USE_AIKAR_FLAGS
            value: "true"
          # UID
          - name: UID
            value: "0"
          # GID
          - name: GID
            value: "1011"
          # Minecraftバージョン
          - name: VERSION
            value: 1.20.2
          # 初期・最大メモリ
          - name: MEMORY
            value: 12G
          # JVM -Dオプション
          - name: JVM_DD_OPTS
            value: "log4j2Fix.loadReflectionUtil:true"
          # JVMオプション
          - name: JVM_OPTS
            value: "-javaagent:Log4j2Fix-1.0.4.jar=l -XX:MaxJavaStackTraceDepth=999999"
          # 再起動前にアナウンスする
          - name: STOP_SERVER_ANNOUNCE_DELAY
            value: "120"
          # yml内のCFG_なんとかを置き換えるためのもの
          - name: ENV_VARIABLE_PREFIX
            value: "CFG_"
          # メタデータ(サーバー内で環境変数で取得可能)
          - name: CFG_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CFG_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CFG_SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
        startupProbe:
          tcpSocket:
            port: 25565
          failureThreshold: 60 # 600秒
          periodSeconds: 10
        volumeMounts:
        - name: server-data
          mountPath: /data
        - name: tab-config
          mountPath: /plugins/TAB/config.yml
          subPath: config.yml
        - name: schem-life
          mountPath: /srv/life
        - name: schem-lifepve
          mountPath: /srv/lifepve
        - name: schem-liferesource
          mountPath: /srv/liferesource
        - name: schem-lifeevent
          mountPath: /srv/lifeevent
        - name: schem-lifeafk
          mountPath: /srv/lifeafk
        - name: schem-lifetown
          mountPath: /srv/lifetown
      volumes:
      - name: server-data
        hostPath:
          path: /srv/lifetown
          type: Directory
      - name: tab-config
        configMap:
          name: common-life-server-tab-config
      - name: schem-life
        hostPath:
          path: /srv/life/plugins/WorldEdit/schematics
          type: Directory
      - name: schem-lifepve
        hostPath:
          path: /srv/lifepve/plugins/WorldEdit/schematics
          type: Directory
      - name: schem-liferesource
        hostPath:
          path: /srv/liferesource/plugins/WorldEdit/schematics
          type: Directory
      - name: schem-lifeevent
        hostPath:
          path: /srv/lifeevent/plugins/WorldEdit/schematics
          type: Directory
      - name: schem-lifeafk
        hostPath:
          path: /srv/lifeafk/plugins/WorldEdit/schematics
          type: Directory
      - name: schem-lifetown
        hostPath:
          path: /srv/lifetown/plugins/FastAsyncWorldEdit/schematics
          type: Directory
      priorityClassName: minecraft-other-server
      terminationGracePeriodSeconds: 180 # 3分
---
apiVersion: v1
kind: Service
metadata:
  name: server-lifetown-svc
spec:
  type: ClusterIP
  selector:
    app: server-lifetown
    stage: production
  ports:
    - port: 25565
      targetPort: 25565
    - port: 8100
      targetPort: 8100
