apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-lifepve1
spec:
  selector:
    matchLabels:
      app: server-lifepve1
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: server-lifepve1
        stage: production
        kuvel.azisaba.net/enable-server-discovery: "true"
        kuvel.azisaba.net/preferred-server-name: lifepve1
    spec:
      nodeName: saba9
      containers:
      - name: server-lifepve1
        # Dockerイメージの指定
        # java11の11の部分を8にしたり17にしたりなど、Minecraftバージョンによって適宜変えてください
        # Javaバージョン早見表
        # 1.14.4以下 ... 8
        # 1.15.x ... 8-11 (9-10はサポート終了)
        # 1.16.x ... 11-16 (12-16はサポート終了)
        # 1.17.x ... 16-17 (16はサポート終了)
        # 1.18.x～1.20.4 ... 17
        # 1.20.5以降 ... 21
        image: itzg/minecraft-server:java11
        workingDir: /data
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1000m"
            memory: "3Gi"
          limits:
            cpu: "6000m"
            memory: "9Gi" # (MAX_)MEMORY + 4Gぐらいにするのがいいらしい
        ports:
          - containerPort: 25565
        env:
          # タイムゾーン
          - name: TZ
            value: "Asia/Tokyo"
          # EULAに同意する
          - name: EULA
            value: "true"
          # サーバーの種類
          - name: TYPE
            value: PAPER
          # 最適化されたJVMフラグを使用する
          - name: USE_AIKAR_FLAGS
            value: "true"
          # スポーン保護
          - name: SPAWN_PROTECTION
            value: "0"
          # オンラインモード
          - name: ONLINE_MODE
            value: "false"
          # コマンドブロックを有効にする
          - name: ENABLE_COMMAND_BLOCK
            value: "true"
          # ネザーを有効にする
          - name: ALLOW_NETHER
            value: "false"
          # "Flying is not enabled on this server"を有効にする
          - name: ALLOW_FLIGHT
            value: "false"
          # 描画距離
          - name: VIEW_DISTANCE
            value: "10"
          # 統計情報をMojangに送信する
          - name: SNOOPER_ENABLED
            value: "false"
          # プレイヤーの実績・進捗解除を全体チャットに流す
          - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
            value: "false"
          # 最大人数
          - name: MAX_PLAYERS
            value: "1000"
          # UID
          - name: UID
            value: "0"
          # GID
          - name: GID
            value: "1012"
          # Minecraftバージョン
          - name: VERSION
            value: 1.15.2
          # 初期・最大メモリ
          - name: MEMORY
            value: 5G
          # ホワイトリスト
          - name: ENABLE_WHITELIST
            value: "false"
          # JVM -Dオプション
          - name: JVM_DD_OPTS
            value: "log4j2Fix.loadReflectionUtil:true"
          # JVMオプション
          - name: JVM_OPTS
            value: "-javaagent:Log4j2Fix-1.0.4.jar=l -DPaper.ignoreWorldDataVersion=true"
          # 再起動前にアナウンスする
          - name: STOP_SERVER_ANNOUNCE_DELAY
            value: "120"
          # yml内のCFG_なんとかを置き換えるためのもの
          - name: ENV_VARIABLE_PREFIX
            value: "CFG_"
          # メタデータ(サーバー内で環境変数で取得可能)
          - name: CFG_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CFG_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CFG_SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
        startupProbe:
          tcpSocket:
            port: 25565
          failureThreshold: 60 # 600秒
          periodSeconds: 10
        volumeMounts:
        - name: server-data
          mountPath: /data
          readOnly: true
        - name: server-data
          mountPath: /data/plugins/MythicMobs
          subPath: plugins/MythicMobs
        - name: itemfixer-data
          mountPath: /data/plugins/ItemFixer
          readOnly: true
        - name: pve1-data
          mountPath: /data/.rcon-cli.env
          subPath: .rcon-cli.env
        - name: pve1-data
          mountPath: /data/.rcon-cli.yaml
          subPath: .rcon-cli.yaml
        - name: pve1-data
          mountPath: /data/.paper.env
          subPath: .paper.env
        - name: pve1-data
          mountPath: /data/.papermc-manifest.json
          subPath: .papermc-manifest.json
        - name: pve1-data
          mountPath: /data/ops.json
          subPath: ops.json
        - name: pve1-data
          mountPath: /data/worlds
          subPath: worlds
        - name: pve1-data
          mountPath: /data/server.properties
          subPath: server.properties
        - name: pve1-data
          mountPath: /data/logs
          subPath: logs
        - name: pve1-data
          mountPath: /data/plugins/PlayerIgnore
          subPath: plugins/PlayerIgnore
        - name: pve1-data
          mountPath: /data/plugins/MythicMobs/Error Logs
          subPath: plugins/MythicMobs/Error Logs
        - name: pve1-data
          mountPath: /data/plugins/TAB
          subPath: plugins/TAB
        - name: pve1-data
          mountPath: /data/plugins/LunaChat
          subPath: plugins/LunaChat
        - name: pve1-data
          mountPath: /data/plugins/BuycraftX
          subPath: plugins/BuycraftX
        - name: pve1-data
          mountPath: /data/plugins/Shopkeepers
          subPath: plugins/Shopkeepers
        - name: pve1-data
          mountPath: /data/plugins/Essentials/userdata
          subPath: plugins/Essentials/userdata
        - name: pve1-data
          mountPath: /data/plugins/ScriptBlockPlus/json/playercount
          subPath: plugins/ScriptBlockPlus/json/playercount
        - name: pve1-data
          mountPath: /data/plugins/JoinNotifier
          subPath: plugins/JoinNotifier
        - name: pve1-data
          mountPath: /data/plugins/LifeCore
          subPath: plugins/LifeCore
        - name: pve1-data
          mountPath: /data/plugins/AzisabaAPI
          subPath: plugins/AzisabaAPI
        - name: pve1-data
          mountPath: /data/plugins/PlayerLimit
          subPath: plugins/PlayerLimit
        - name: pve1-data
          mountPath: /data/plugins/FastAsyncWorldEdit
          subPath: plugins/FastAsyncWorldEdit
        - name: pve1-data
          mountPath: /data/plugins/AzisabaAds
          subPath: plugins/AzisabaAds
        - name: tab-config
          mountPath: /plugins/TAB/config.yml
          subPath: config.yml
      volumes:
      - name: server-data
        hostPath:
          path: /srv/lifepve
          type: Directory
      - name: itemfixer-data
        hostPath:
          path: /srv/life/plugins/ItemFixer
          type: Directory
      - name: pve1-data
        hostPath:
          path: /srv/lifepve1
          type: Directory
      - name: tab-config
        configMap:
          name: common-life-server-tab-config
      priorityClassName: minecraft-other-server
      terminationGracePeriodSeconds: 180 # 3分
---
apiVersion: v1
kind: Service
metadata:
  name: server-lifepve1-svc
spec:
  type: ClusterIP
  selector:
    app: server-lifepve1
    stage: production
  ports:
    - port: 25565
      targetPort: 25565
