apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-lifeart
spec:
  selector:
    matchLabels:
      app: server-lifeart
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: server-lifeart
        stage: production
        kuvel.azisaba.net/enable-server-discovery: "true"
        kuvel.azisaba.net/preferred-server-name: lifeart
    spec:
      nodeName: saba10 # it does not need to be on saba10, we just need to avoid saba9
      containers:
        - name: server-lifeart
          # Dockerイメージの指定
          # Javaバージョン早見表
          # 1.14.4以下 ... 8
          # 1.15.x ... 8-11 (9-10はサポート終了)
          # 1.16.x ... 11-16 (12-16はサポート終了)
          # 1.17.x ... 16-17 (16はサポート終了)
          # 1.18.x～1.20.4 ... 17 (一部は21まで可能)
          # 1.20.5以降 ... 21
          image: itzg/minecraft-server:java11
          workingDir: /data
          imagePullPolicy: Always
          resources:
            requests:
              memory: "6Gi"
            limits:
              cpu: "10000m"
          ports:
            - containerPort: 25565
            - containerPort: 5005
            - containerPort: 9225
          env:
            # タイムゾーン
            - name: TZ
              value: "Asia/Tokyo"
            # EULAに同意する
            - name: EULA
              value: "true"
            # サーバーの種類
            - name: TYPE
              value: PAPER
            # 最適化されたJVMフラグを使用する
            - name: USE_AIKAR_FLAGS
              value: "true"
            # Minecraftバージョン
            - name: VERSION
              value: 1.15.2
            # 最大メモリ
            - name: MEMORY
              value: 6G
            # JVM -Dオプション
            - name: JVM_DD_OPTS
              value: "Paper.IgnoreJavaVersion:true"
            # yml内のCFG_なんとかを置き換えるためのもの
            - name: ENV_VARIABLE_PREFIX
              value: "CFG_"
            # メタデータ(サーバー内で環境変数で取得可能)
            - name: CFG_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CFG_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CFG_SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
          startupProbe:
            tcpSocket:
              port: 25565
            failureThreshold: 60 # 600秒
            periodSeconds: 10
          volumeMounts:
            - name: server-data
              mountPath: /data
            - name: tab-config
              mountPath: /plugins/TAB/config.yml
              subPath: config.yml
      volumes:
        - name: server-data
          persistentVolumeClaim:
            claimName: server-lifeart-data-claim
        - name: tab-config
          configMap:
            name: common-life-server-tab-config
      priorityClassName: minecraft-other-server
      terminationGracePeriodSeconds: 60 # 1分
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-lifeart-data-claim
spec:
  storageClassName: nfs-client
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: server-lifeart-svc
spec:
  type: ClusterIP
  selector:
    app: server-lifeart
    stage: production
  ports:
    - port: 25565
      targetPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: server-lifeart-prometheus-exporter-svc
spec:
  type: ClusterIP
  selector:
    app: server-lifeart
    stage: production
  ports:
    - port: 9225
      targetPort: 9225
