apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-coasts-bonus-stage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-coasts-bonus-stage
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-coasts-bonus-stage
subjects:
  - kind: ServiceAccount
    name: server-coasts-bonus-stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: server-coasts-bonus-stage
