apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-lgw2sv2
spec:
  selector:
    matchLabels:
      app: server-lgw2sv2
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: server-lgw2sv2
        stage: production
        kuvel.azisaba.net/enable-server-discovery: "true"
        kuvel.azisaba.net/preferred-server-name: lgw2sv2
    spec:
      nodeName: saba8
      containers:
      - name: server-lgw2sv2
        # Dockerイメージの指定
        # java11の11の部分を8にしたり17にしたりなど、Minecraftバージョンによって適宜変えてください
        # Javaバージョン早見表
        # 1.14.4以下 ... 8
        # 1.15.x ... 8-11 (9-10はサポート終了)
        # 1.16.x ... 11-16 (12-16はサポート終了)
        # 1.17.x ... 16-17 (16はサポート終了)
        # 1.18.x～1.20.4 ... 17 (一部は21まで可能)
        # 1.20.5以降 ... 21
        image: itzg/minecraft-server:java17
        workingDir: /data
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1000m"
            memory: "4Gi"
          limits:
            cpu: "10000m"
            memory: "16Gi"
        ports:
          - containerPort: 25565
        env:
          # タイムゾーン
          - name: TZ
            value: "Asia/Tokyo"
          # EULAに同意する
          - name: EULA
            value: "true"
          # サーバーの種類
          - name: TYPE
            value: PAPER
          # 最適化されたJVMフラグを使用する
          - name: USE_AIKAR_FLAGS
            value: "true"
          # UID
          - name: UID
            value: "0"
          # GID
          - name: GID
            value: "1021"
          # Minecraftバージョン
          - name: VERSION
            value: 1.16.5
          # 初期・最大メモリ
          - name: MEMORY
            value: 4G
          # JVM -Dオプション
          - name: JVM_DD_OPTS
            value: "Paper.IgnoreJavaVersion:true"
          # yml内のCFG_なんとかを置き換えるためのもの
          - name: ENV_VARIABLE_PREFIX
            value: "CFG_"
          # メタデータ(サーバー内で環境変数で取得可能)
          - name: CFG_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CFG_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CFG_SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
        startupProbe:
          tcpSocket:
            port: 25565
          failureThreshold: 60 # 600秒
          periodSeconds: 10
        volumeMounts:
        - name: server-data
          mountPath: /data
        - name: server-data
          mountPath: /data/plugins/LeonGunWar/main.yml
          subPath: plugins/LeonGunWar/main.yml
          readOnly: true
        - name: lgw2-data
          mountPath: /data/shared
          subPath: shared
        - name: lgw2-data
          mountPath: /data/plugins/LeonCSAddon
          subPath: plugins/LeonCSAddon
          readOnly: true
        - name: lgw2-data
          mountPath: /data/plugins/LeonGunWar
          subPath: plugins/LeonGunWar
          readOnly: true
        - name: lgw2-data
          mountPath: /data/plugins/CrackShot
          subPath: plugins/CrackShot
          readOnly: true
        - name: lgw2-data
          mountPath: /data/plugins/CrackShotPlus
          subPath: plugins/CrackShotPlus
          readOnly: true
        - name: lgw2-data
          mountPath: /data/plugins/AgetarouUniqueGuns
          subPath: plugins/AgetarouUniqueGuns
          readOnly: true
        - name: lgw2-data
          mountPath: /data/plugins/NameChangeAutomation/NameChangeInfo
          subPath: plugins/NameChangeAutomation/NameChangeInfo
          readOnly: true
        - name: tab-config
          mountPath: /plugins/TAB/config.yml
          subPath: config.yml
      volumes:
      - name: server-data
        hostPath:
          path: /srv/lgw2sv2
          type: Directory
      - name: lgw2-data
        hostPath:
          path: /srv/lgw2
          type: Directory
      - name: tab-config
        configMap:
          name: common-lgw2-server-tab-config
      priorityClassName: minecraft-other-server
      terminationGracePeriodSeconds: 60 # 1分
---
apiVersion: v1
kind: Service
metadata:
  name: server-lgw2sv2-svc
spec:
  type: ClusterIP
  selector:
    app: server-lgw2sv2
    stage: production
  ports:
    - port: 25565
      targetPort: 25565
